version: '3.8'

services:
  # NestJS Integration API
  nest-integration-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: idurar-nest-integration-api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - idurar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Development version
  nest-integration-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: idurar-nest-integration-api-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - idurar-network
    restart: unless-stopped
    profiles:
      - dev

networks:
  idurar-network:
    driver: bridge
    external: false